### ISSUE TITLE
Not working on Raspberry Pi 5 (Unsupported platform)

### ISSUE THREAD

**Issue by angelo-v** [rhasspy/wyoming-porcupine1#5]
Steps to reproduce:

Try to run the docker image on an Raspberry Pi 5:

```
> $ docker run -it -p 10400:10400 rhasspy/wyoming-porcupine1
WARNING: Please be advised that this device (CPU part = 0xd0b) is not officially supported by Picovoice. Falling back to the armv6-based library. This is not tested nor optimal.                                 
 Traceback (most recent call last):                                                                                                                                                                                
   File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                                         
   File "<frozen runpy>", line 88, in _run_code                                                                                                                                                                    
   File "/usr/src/.venv/lib/python3.11/site-packages/wyoming_porcupine1/__main__.py", line 14, in <module>                                                                                                         
     import pvporcupine                                                                                                                                                                                            
   File "/usr/src/.venv/lib/python3.11/site-packages/pvporcupine/__init__.py", line 15, in <module>                                                                                                                
     LIBRARY_PATH = pv_library_path('')                                                                                                                                                                            
                    ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                            
   File "/usr/src/.venv/lib/python3.11/site-packages/pvporcupine/util.py", line 94, in pv_library_path                                                                                                             
     raise NotImplementedError('Unsupported platform.')                                                                                                                                                            
 NotImplementedError: Unsupported platform.      
```

```
> $ uname -a 
Linux raspberrypi 6.6.51+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux
```

**Comment by angelo-v** [comment]
Same error when running it without docker via
```
git clone https://github.com/rhasspy/wyoming-porcupine1.git
cd wyoming-procupine1
script/setup
script/run
```
